# Generated by Django 5.1.6 on 2025-02-27 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocked',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='blocked',
            index=models.Index(fields=['blocker'], name='core_blocke_blocker_8d4f61_idx'),
        ),
        migrations.AddIndex(
            model_name='blocked',
            index=models.Index(fields=['blocked'], name='core_blocke_blocked_050afe_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='core_commen_post_id_6aa857_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='core_commen_user_id_98f009_idx'),
        ),
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['follower', 'following'], name='core_follow_followe_294198_idx'),
        ),
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['created_at'], name='core_follow_created_8d82ca_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='core_like_user_id_a989fd_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='core_like_post_id_777ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['owner'], name='core_post_owner_i_3a2958_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='core_post_created_2da706_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='core_profil_user_id_155486_idx'),
        ),
    ]
