# Generated by Django 5.1.6 on 2025-02-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blocked_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='privace_settings',
            new_name='privacy_settings',
        ),
    ]
