# Generated by Django 5.1.6 on 2025-03-03 16:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_privace_settings_profile_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.create_custom_path_post),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, default='static/default_image/default_profile.png', null=True, upload_to=core.models.create_custom_path_profile),
        ),
    ]
